[env]
CARGO_MAKE_RUN_CODECOV = true
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_CARGO_BUILD_TEST_FLAGS = "--lib"
CARGO_MAKE_COVERAGE_PROVIDER = "kcov"

[tasks.test-cargo]
command = "cargo"
args = ["test", "--profile", "dev-fast", "--", "--nocapture"]

[tasks.test-cargo-ci]
command = "cargo"
args = ["test", "--profile", "ci", "--", "--nocapture"]

[tasks.test-cargo-release]
command = "cargo"
args = ["test", "--profile", "release", "--", "--nocapture"]

[tasks.build-dev-fast]
command = "cargo"
args = ["build", "--profile", "dev-fast"]

[tasks.build-release]
command = "cargo"
args = ["build", "--profile", "release"]

[tasks.bench]
command = "cargo"
args = ["bench", "--profile", "bench"]

[tasks.dev]
dependencies = ["build-dev-fast", "test-cargo"]

[tasks.build-all]
dependencies = ["build-release"]

[tasks.test-all]
dependencies = ["test-cargo-release", "test-store-js", "test-store-js"]

[tasks.ci]
dependencies = ["build-release", "test-cargo-ci", "test-store-js"]
