use cid::Cid;
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use thiserror::Error;

use crate::auth::jws::{AuthorizationPayload, PermissionGrantInvocation, SigningPayload};
use crate::cid::generate_cid_from_serialized;

use super::super::{fields::MessageFields, Fields, Message};
use super::{Descriptor, RecordsWriteDescriptor};

/// ValidationError represents an error that occurs during validation of a message descriptor.
#[derive(Serialize, Deserialize, Error, Debug)]
#[error("Validation error: {message}")]
pub struct ValidationError {
    /// The error message.
    pub message: String,
}

pub trait MessageParameters {
    type Descriptor: MessageDescriptor;
    type Fields: MessageFields;

    #[allow(async_fn_in_trait)]
    async fn build(&self) -> Result<(Self::Descriptor, Option<Self::Fields>), ValidationError> {
        Err(ValidationError {
            message: String::from("not implemented"),
        })
    }

    fn delegated_grant(&self) -> Option<Message<RecordsWriteDescriptor>> {
        None
    }

    fn permission_grant_id(&self) -> Option<String> {
        None
    }

    fn permission_grant_invocation(&self) -> Result<PermissionGrantInvocation, ValidationError> {
        Ok(self
            .permission_grant_id()
            .map(PermissionGrantInvocation::Single)
            .unwrap_or(PermissionGrantInvocation::None))
    }

    fn protocol_rule(&self) -> Option<String> {
        None
    }

    fn authorization_payload(
        &self,
        descriptor_cid: Cid,
        fields: &Self::Fields,
        delegated_grant_id: Option<Cid>,
        permission_grant: PermissionGrantInvocation,
        protocol_role: Option<String>,
    ) -> Result<SigningPayload, ValidationError> {
        let _ = fields;
        AuthorizationPayload::new(
            descriptor_cid,
            delegated_grant_id,
            permission_grant,
            protocol_role,
        )
        .map(SigningPayload::Generic)
        .map_err(|e| ValidationError {
            message: format!("Failed to create authorization payload: {e}"),
        })
    }
}

impl MessageParameters for () {
    type Descriptor = Descriptor;
    type Fields = Fields;
}

/// ConcreteDescriptor is implemented by every concrete message descriptor (normally via the
/// `#[descriptor]`/`#[interface]` macros). It exposes the descriptor's `interface`/`method` as
/// associated constants, which back both the typed deserialization guard and union dispatch.
pub trait ConcreteDescriptor: MessageDescriptor + Serialize + DeserializeOwned + PartialEq {
    const INTERFACE: &'static str;
    const METHOD: &'static str;
    /// The concatenated `INTERFACE`+`METHOD` handler key (e.g. `RecordsWrite`), built at compile
    /// time by the `#[descriptor]` macro. Backs [`MessageKind::as_str`](super::MessageKind::as_str)
    /// without a runtime allocation.
    const KEY: &'static str;
    /// The JSON-schema identifier validating this descriptor's messages, or `None` for descriptors
    /// with no published schema. Set via the
    /// `#[descriptor(schema_id = …)]` attribute; backs the descriptor-derived schema lookup in
    /// `dwn::validation`.
    const SCHEMA_ID: Option<&'static str>;
}

/// FromDescriptor is implemented by every concrete message descriptor (normally via the
/// `#[interface]` macro). It downcasts a borrowed `Descriptor` union to the concrete descriptor
/// type, returning a borrowed reference (clone at the call site if an owned value is needed).
pub trait FromDescriptor: ConcreteDescriptor {
    fn from_descriptor(descriptor: &Descriptor) -> Result<&Self, ValidationError>;
}

/// Implemented for each interface union (`Records`/`Protocols`/`Messages`), generated by the
/// `#[interface]` macro. Exposes the union's interface name and the full set of descriptor kinds
/// it can deserialize as `(interface, method, has_handler)` tuples.
pub trait InterfaceUnion {
    const INTERFACE: &'static str;
    const KINDS: &'static [(&'static str, &'static str)];
}

/// MessageDescriptor is a trait that all message descriptors must implement.
/// It provides the interface and method for the message descriptor. The generic `Descriptor`
/// implements this trait for use when the concrete type is not known. Concrete Descriptor types
/// implement this trait directly (or use the derive macro).
pub trait MessageDescriptor: Serialize + DeserializeOwned + PartialEq {
    type Fields: MessageFields
        + Serialize
        + DeserializeOwned
        + std::fmt::Debug
        + PartialEq
        + Send
        + Sync
        + Clone;

    type Parameters: MessageParameters + Send + Sync;

    fn interface(&self) -> &'static str;
    fn method(&self) -> &'static str;

    fn cid(&self) -> cid::Cid {
        generate_cid_from_serialized(self)
            .expect("Failed to generate CID from serialized message descriptor")
    }
}

pub trait MessageValidator {
    fn validate(&self) -> Result<(), ValidationError> {
        Err(ValidationError {
            message: String::from("not implemented"),
        })
    }
}
