//! Regression coverage for a database written with the pre-A256CTR Rust
//! encryption envelope. The fixed envelope/ciphertext vector is intentionally
//! legacy-shaped (`protected`/`iv`/`tag`/`recipients`), never generated by the
//! current RecordsWrite builder.

mod common;

use std::collections::BTreeMap;
use std::sync::Arc;

use base64::Engine;
use bytes::Bytes;
use dwn_rs_core::cid::generate_dag_pb_cid_from_bytes;
use dwn_rs_core::stores::wake::WakePublishHandler;
use dwn_rs_core::stores::{DataStore, MessageStore};
use dwn_rs_core::{Descriptor, Fields, Filters, Message, Value};
use futures_util::{stream, TryStreamExt};
use rusqlite::Connection;
use serde_json::json;

use dwn_rs_stores::SqliteStore;

const TENANT: &str = "did:example:alice";
const RECORD_ID: &str = "legacy-record";
const PLAINTEXT: &[u8] = b"legacy plaintext";
const CIPHERTEXT: &str = "S-Dj9d2J4RHMA6JWko_bqw";
const PRIVATE_JWK: &str = r#"{"kty":"OKP","crv":"X25519","x":"Xf7dO2vUf2-ijuFdlp1bsOpTd01Ii9r53xxuASSz7yI","d":"AwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwM"}"#;
const LEGACY_ENCRYPTION: &str = r#"{"protected":"eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImVuYyI6IkEyNTZHQ00ifQ","iv":"CQkJCQkJCQkJCQkJ","tag":"pr5lZdaYTajVA0gqMvwlQw","recipients":[{"header":{"kid":"legacy-key","epk":{"kty":"OKP","crv":"X25519","x":"B6r_Pp_BZydVRPTDpqF82Dfy7G54zYpXsePfs8wDWnY"},"derivationScheme":"protocolPath"},"encrypted_key":"T42gGabDj__6KG89Wz97VBmlDEmkJj3HjLh-dPX-KzEbTi6z6DMLoA"}]}"#;

#[tokio::test]
async fn sqlite_upgrade_reads_and_decrypts_legacy_records_without_rewriting_message_json() {
    // Serialize file-backed tests process-wide (issue #255).
    let _disk = common::disk_test_guard().await;
    let ciphertext = base64::prelude::BASE64_URL_SAFE_NO_PAD
        .decode(CIPHERTEXT)
        .unwrap();
    let data_cid = generate_dag_pb_cid_from_bytes(&ciphertext).to_string();
    let encryption: serde_json::Value = serde_json::from_str(LEGACY_ENCRYPTION).unwrap();
    let message: Message<Descriptor> = serde_json::from_value(json!({
        "descriptor": {
            "interface": "Records",
            "method": "Write",
            "protocol": "https://example.com/legacy",
            "protocolPath": "record",
            "dataCid": data_cid,
            "dataSize": ciphertext.len(),
            "dataFormat": "application/octet-stream",
            "dateCreated": "2025-01-01T00:00:00.000000Z",
            "messageTimestamp": "2025-01-01T00:00:00.000000Z"
        },
        "recordId": RECORD_ID,
        "encryption": encryption
    }))
    .expect("legacy RecordsWrite fixture must deserialize");
    let message_cid = message.cid().unwrap().to_string();

    let temporary = tempfile::tempdir().unwrap();
    let path = temporary.path().join("legacy-encryption.sqlite");
    let mut pre_upgrade = SqliteStore::new(&path, WakePublishHandler::new(Arc::new(())));
    MessageStore::open(&mut pre_upgrade).await.unwrap();
    let indexes = BTreeMap::from([(
        "messageTimestamp".to_string(),
        Value::String("2025-01-01T00:00:00.000000Z".to_string()),
    )]);
    MessageStore::put(&pre_upgrade, TENANT, message, indexes)
        .await
        .unwrap();
    DataStore::put(
        &pre_upgrade,
        TENANT,
        RECORD_ID,
        &data_cid,
        stream::iter(vec![Bytes::from(ciphertext.clone())]),
    )
    .await
    .unwrap();
    MessageStore::close(&mut pre_upgrade).await;
    // `close` prevents the pools from handing out more connections, but the
    // store still owns the initialized pools. Drop it before opening the same
    // database through rusqlite or another SqliteStore so every platform
    // releases the SQLite handles deterministically.
    drop(pre_upgrade);
    let message_json_before = stored_message_json(&path, &message_cid);

    let mut upgraded = SqliteStore::new(&path, WakePublishHandler::new(Arc::new(())));
    MessageStore::open(&mut upgraded).await.unwrap();
    let by_get = MessageStore::get(&upgraded, TENANT, &message_cid)
        .await
        .unwrap()
        .expect("legacy record through get");
    let by_query = MessageStore::query(&upgraded, TENANT, Filters::default(), None, None)
        .await
        .unwrap()
        .messages
        .into_iter()
        .next()
        .expect("legacy record through query");
    let stored_ciphertext = DataStore::get(&upgraded, TENANT, RECORD_ID, &data_cid)
        .await
        .unwrap()
        .expect("legacy ciphertext")
        .data_stream
        .try_fold(Vec::new(), |mut bytes, chunk| async move {
            bytes.extend_from_slice(&chunk);
            Ok::<_, std::io::Error>(bytes)
        })
        .await
        .unwrap();
    MessageStore::close(&mut upgraded).await;
    drop(upgraded);

    let private_jwk = serde_json::from_str(PRIVATE_JWK).unwrap();
    for message in [by_get, by_query] {
        let encryption = match message.fields {
            Fields::Write(fields) => fields.encryption.expect("legacy encryption"),
            other => panic!("expected RecordsWrite fields, got {other:?}"),
        };
        assert!(encryption.is_legacy_jwe());
        assert_eq!(
            encryption
                .decrypt(&private_jwk, &stored_ciphertext)
                .unwrap(),
            PLAINTEXT
        );
    }
    assert_eq!(
        stored_message_json(&path, &message_cid),
        message_json_before
    );
}

fn stored_message_json(path: &std::path::Path, message_cid: &str) -> String {
    Connection::open(path)
        .unwrap()
        .query_row(
            "SELECT message_json FROM messages WHERE tenant = ?1 AND message_cid = ?2",
            [TENANT, message_cid],
            |row| row.get(0),
        )
        .unwrap()
}
